GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJOYXVmYWwgRmFraHJpIiwiZW1haWwiOiJuZmFraHJpMTQxMkBnbWFpbC5jb20iLCJpYXQiOjE2NDg2MjgwNzMsImV4cCI6MTY0ODYyOTA3M30.Xugi_SCqBHMjdU5PZhB4HTzWooA8CNAaOUviJ_hLVJ4

###
GET http://localhost:5000/allusers
Content-Type: application/json

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name" : "Luqman",
    "email" : "luqman@gmail.com",
    "password" : "123456",
    "confpassword" : "123456"
}


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "nfakhri1412@gmail.com",
    "password" : "123456"
}

###
GET http://localhost:5000/token
Content-Type: application/json

###
DELETE  http://localhost:5000/logout
Content-Type: application/json

###
POST  http://localhost:5000/inputsurat
Content-Type: application/json

{
    "tanggal": "{CurrentDatetime}",
    "no_surat" : "A/01.001/DK/I/2021",
    "keterangan": "Test Surat"
}

###
GET http://localhost:5000/tampilsurat

###
DELETE http://localhost:5000/tampilsurat
Content-Type: application/json

{
    "id" : 2
}

###
put http://localhost:5000/tampilsurat
Content-Type: application/json

{
    "id" : 3,
    "tanggal": "{CurrentDatetime}",
    "no_surat" : "A/01.001/DK/I/2021",
    "keterangan": "Test Surat xixixi"
}


